### ISSUE TITLE
Widget does not react on change of default enumeration widget

### ISSUE THREAD

**Issue by melvingrootenboers** [ChrisdeG/EnumToggle#4]
1. Run testproject
2. Open page "Normal"
3. Select "Medior" in the radiobuttonlist

Expected:
EnumToggle widget shows image of enumeration value "Medior"

Actual:
EnumToggle widget shows default picture

![image](https://cloud.githubusercontent.com/assets/10810429/11775729/7ff428a2-a241-11e5-8d36-47602030fd7f.png)

**Comment by ChrisdeG** [comment]
This is fixed.
